# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home page
email: kirylchyk@gmail.com
description: > # this means to ignore newlines until "baseurl:"This resource is designed to help to build up analytical reports in different spheres to foster effectiveness and reduce risks. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://analytics-in-use.com" # the base hostname & protocol for your site
twitter_username: kirylchyk
github_username:  kirylchyk

# Build settings
markdown: kramdown
